language: php
php:
  - 5.6
  - 5.5
before_install:
  - gem install mailcatcher
  - mailcatcher --http-ip 127.0.0.1 --http-port 1081 --smtp-ip 127.0.0.1 --smtp-port 1026
  - pip install maildump
  - maildump --http-ip 127.0.0.1 --http-port 1080 --smtp-ip 127.0.0.1 --smtp-port 1025
  - cd test
  - composer update
  - php vendor/bin/codecept build

script: php vendor/bin/codecept run -d
