language: php
php:
  - 5.6
  - 5.5
before_install:
  - echo 'date.timezone = "Etc/GMT"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - gem install mailcatcher
  - mailcatcher --http-ip 127.0.0.1 --http-port 1081 --smtp-ip 127.0.0.1 --smtp-port 1026
  - pip install --user maildump
  - maildump --http-ip 127.0.0.1 --http-port 1080 --smtp-ip 127.0.0.1 --smtp-port 1025 --pidfile ~/maildump.pid
  - pip install --user lathermail
  - lathermail --api-host 127.0.0.1 --api-port 1082 --smtp-host 127.0.0.1 --smtp-port 1027 </dev/null &>/dev/null &
  - cd test
  - composer self-update
  - composer install --prefer-source
  - php vendor/bin/codecept build

script:
  - php vendor/bin/codecept run -d --coverage-xml acceptance.xml

after_success:
  - travis_retry php vendor/bin/coveralls -v

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/pip
    - $HOME/.local/lib
    - $HOME/.local/include
    - $HOME/.local/bin
